###create products
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "tv 75 p",
  "description": "75 pulgadas",
  "price": 20000,
  "stock": 20,
  "image": "/home/dsambran/workspaces/microservices-rabbitmq-nestjs-skeleton/nest-mongoose/request/brands/products",
  "brand": "636f967a75f791519bc699d7"
}

###get all products
GET http://localhost:3000/products

###get one product
GET http://localhost:3000/products/636bc8a5bc73f5e7ac98e76c


###delete one