@url = http://localhost:3000/brands

###create products
POST {{url}}
Content-Type: application/json

{
  "name": "lg",
  "image": "https://img.freepik.com/vector-gratis/casa-dos-pisos_1308-16176.jpg"
}

### get all brands
GET {{url}}

###get one product
GET {{url}}/636f967a75f791519bc699d7


###delete one